// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: service/rfq/error.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_ERROR_UNDEFINED ErrCode = 0
	ErrCode_ERROR_COMMON    ErrCode = 1
	// generic error code for all invalid requests that are not specified below
	ErrCode_ERROR_INVALID_REQUEST ErrCode = 2
	// returned in Quote() if the MM rejects the quote
	ErrCode_ERROR_MM_REJECTED_QUOTE ErrCode = 3
	// returned in Quote() if the price's valid_thru is passed
	ErrCode_ERROR_PRICE_DEADLINE ErrCode = 4
	// returned in Quote() if the price sig is invalid
	ErrCode_ERROR_INVALID_SIG ErrCode = 5
	// returned in Quote() if the src/dst deadline is invalid
	ErrCode_ERROR_INVALID_DEADLINE ErrCode = 6
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0: "ERROR_UNDEFINED",
		1: "ERROR_COMMON",
		2: "ERROR_INVALID_REQUEST",
		3: "ERROR_MM_REJECTED_QUOTE",
		4: "ERROR_PRICE_DEADLINE",
		5: "ERROR_INVALID_SIG",
		6: "ERROR_INVALID_DEADLINE",
	}
	ErrCode_value = map[string]int32{
		"ERROR_UNDEFINED":         0,
		"ERROR_COMMON":            1,
		"ERROR_INVALID_REQUEST":   2,
		"ERROR_MM_REJECTED_QUOTE": 3,
		"ERROR_PRICE_DEADLINE":    4,
		"ERROR_INVALID_SIG":       5,
		"ERROR_INVALID_DEADLINE":  6,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_service_rfq_error_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_service_rfq_error_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_service_rfq_error_proto_rawDescGZIP(), []int{0}
}

var File_service_rfq_error_proto protoreflect.FileDescriptor

var file_service_rfq_error_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x72, 0x66, 0x71, 0x2f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x72, 0x66, 0x71, 0x2a, 0xb5, 0x01, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x55, 0x4e, 0x44, 0x45,
	0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45,
	0x53, 0x54, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x4d, 0x4d,
	0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x5f, 0x51, 0x55, 0x4f, 0x54, 0x45, 0x10,
	0x03, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x50, 0x52, 0x49, 0x43, 0x45,
	0x5f, 0x44, 0x45, 0x41, 0x44, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x53, 0x49, 0x47,
	0x10, 0x05, 0x12, 0x1a, 0x0a, 0x16, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x44, 0x45, 0x41, 0x44, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x06, 0x42, 0x3c,
	0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x65, 0x6c,
	0x65, 0x72, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x70, 0x65, 0x74, 0x69, 0x2d,
	0x72, 0x66, 0x71, 0x2d, 0x6d, 0x6d, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x72, 0x66, 0x71, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_rfq_error_proto_rawDescOnce sync.Once
	file_service_rfq_error_proto_rawDescData = file_service_rfq_error_proto_rawDesc
)

func file_service_rfq_error_proto_rawDescGZIP() []byte {
	file_service_rfq_error_proto_rawDescOnce.Do(func() {
		file_service_rfq_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_rfq_error_proto_rawDescData)
	})
	return file_service_rfq_error_proto_rawDescData
}

var file_service_rfq_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_rfq_error_proto_goTypes = []interface{}{
	(ErrCode)(0), // 0: service.rfq.ErrCode
}
var file_service_rfq_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_rfq_error_proto_init() }
func file_service_rfq_error_proto_init() {
	if File_service_rfq_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_rfq_error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_rfq_error_proto_goTypes,
		DependencyIndexes: file_service_rfq_error_proto_depIdxs,
		EnumInfos:         file_service_rfq_error_proto_enumTypes,
	}.Build()
	File_service_rfq_error_proto = out.File
	file_service_rfq_error_proto_rawDesc = nil
	file_service_rfq_error_proto_goTypes = nil
	file_service_rfq_error_proto_depIdxs = nil
}
