[[lp]]
chainid = 5
keystore = "./eth-ks/<your-test-account>.json"
passphrase = "<your-password>"
releasenative = false

[[lp.liqs]]
address = "0xf4B2cbc3bA04c478F0dC824f4806aC39982Dce73"
symbol = "USDT"
amount = "5000000000"
#approve = "1000000000000"
decimals = 6
# in second
freezetime = 300
[[lp.liqs]]
address = "0xCbE56b00d173A26a5978cE90Db2E33622fD95A28"
symbol = "USDC"
amount = "5000000000"
#approve = "1000000000000"
decimals = 6
# in second
freezetime = 300
[[lp.liqs]]
address = "0x5D3c0F4cA5EE99f8E8F59Ff9A5fAb04F6a7e007f"
symbol = "CELR"
amount = "0"
#approve = "1000000000000000000000000"
decimals = 18
# in second
freezetime = 300
[[lp.liqs]]
address = "0xffffffffffffffffffffffffffffffffffffffff"
symbol = "ETH"
#amount = "0"
decimals = 18
# in second
freezetime = 200

[[lp]]
chainid = 97
keystore = "./eth-ks/<your-test-account>.json"
passphrase = "<your-password>"
releasenative = false

[[lp.liqs]]
address = "0x7d43AABC515C356145049227CeE54B608342c0ad"
symbol = "USDT"
#amount = "0"
#approve = "1000000000000"
decimals = 6
# in second
freezetime = 300
[[lp.liqs]]
address = "0x855fC87f7F14Db747ef27603b02bAe579ba947B6"
symbol = "USDC"
#amount = "0"
#approve = "1000000000000"
decimals = 6
# in second
freezetime = 300
[[lp.liqs]]
address = "0x5471ea8f739dd37E9B81Be9c5c77754D8AA953E4"
symbol = "CELR"
#amount = "0"
#approve = "1000000000000000000000000"
decimals = 18
# in second
freezetime = 300
[[lp.liqs]]
address = "0xffffffffffffffffffffffffffffffffffffffff"
symbol = "BNB"
#amount = "0"
decimals = 18
# in second
freezetime = 200