[priceprovider]
url = "https://cbridge-stat.s3.us-west-2.amazonaws.com/prod2/cbridge-price.json"

[rfqserver]
url = ""
apikey = ""

[requestsigner]
chainid = 5
# keystore(file path) and passphrase is needed, if requestSigner is not lp
keystore = ""
passphrase = ""

[mm]
grpcPort = 5555
grpcGatewayPort=6666
# in second
priceValidPeriod = 300
dstTransferPeriod = 600
# if faled to report token configs to rfq server, mm will be stucked and retry every <reportRetryPeriod> seconds until success.
reportRetryPeriod = 5
processPeriod = 5
tpPolicyList = ["Any2Of=5-USDT,97-USDT","OneOf=5-USDC,97-USDC"]
# change lightMM to true if it is light mm
lightMM = false
# change host to "0.0.0.0" if svc opening to public web directly
host="localhost"